name: Generate Snake Animation

on:
  schedule:
    - cron: "0 0 * * *" # Cada día a medianoche UTC
  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repositorio
        uses: actions/checkout@v3

      - name: Generar Snake
        uses: Platane/snk@master
        with:
          github_user_name: TU_USUARIO
          outputs: |
            dist/github-contribution-grid-snake.svg

      - name: Subir archivo generado
        uses: EndBug/add-and-commit@v9
        with:
          author_name: github-actions
          author_email: github-actions@github.com
          message: "Actualiza Snake Game de contribuciones"
          add: "dist/github-contribution-grid-snake.svg"

      - name: Subir al branch output
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
          publish_branch: output

